CREATE DATABASE fixturedb;
USE fixturedb;

CREATE TABLE OCTA_SPACE_FIXTURE (
  FIXTURE_ID INT AUTO_INCREMENT PRIMARY KEY,
  START_DATE DATE,
  END_DATE DATE,
  FIXTURE_DESCR VARCHAR(255),
  FIXTURE_TYPE VARCHAR(100),
  FIXTURE_CODE VARCHAR(50),
  FIXTURE_STATUS VARCHAR(50),
  FIXTURE_DIMENSION_UNIT VARCHAR(20),
  FIXTURE_DIMENTION_HEIGHT FLOAT,
  FIXTURE_DIMENTION_WIDTH FLOAT,
  FIXTURE_DIMENTION_DEPTH FLOAT,
  FIXTURE_FLOOR_TO_SHELF_HEIGHT FLOAT,
  FIXTURE_CAPACITY_UNITS INT,
  FIXTURE_AVAIL_FOR_RENT BOOLEAN,
  FIXTURE_UNIQUE_IDENTIFIER VARCHAR(100),
  FIXTURE_LOCATION VARCHAR(100),
  FIXTURE_CATEGORY VARCHAR(100)
);

CREATE TABLE OCTA_SPACE_FIXTURE_IMAGES (
  IMAGE_ID INT AUTO_INCREMENT PRIMARY KEY,
  FIXTURE_ID INT,
  IMAGE LONGBLOB,
  IMAGE_DESCR VARCHAR(255),
  CREATED_BY VARCHAR(100),
  CREATED_DT DATETIME DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (FIXTURE_ID) REFERENCES OCTA_SPACE_FIXTURE(FIXTURE_ID) ON DELETE CASCADE
);

CREATE TABLE OCTA_SPACE_FIXTURE_CATEGORIES (
  FIXTURE_ID INT,
  FIXTURE_CATEGORY VARCHAR(100),
  ALLOCATED_SPACE FLOAT,
  ELASTICITY_COEFFICIENT FLOAT,
  PRIMARY KEY (FIXTURE_ID, FIXTURE_CATEGORY),
  FOREIGN KEY (FIXTURE_ID) REFERENCES OCTA_SPACE_FIXTURE(FIXTURE_ID) ON DELETE CASCADE
);


ALTER TABLE OCTA_SPACE_FIXTURE ADD COLUMN categories JSON;


-- ------------------------------------- 
show tables;
select * from octa_space_fixture;
select * from octa_space_fixture_categories;
select * from octa_space_fixture_images;